services:
  zoo:
    image: zookeeper
    restart: always
    hostname: zoo
    container_name: zoo
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo:2888:3888
    networks:
      - dokploy-network

  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
    depends_on:
      - zoo
    networks:
      - dokploy-network

  app:
    build: ./main/
    ports:
      - "8000:8000"
    volumes:
      - ./main/users.db:/app/users.db
    environment:
      SUPABASE_URL: $SUPABASE_URL
      SUPABASE_API_KEY: $SUPABASE_API_KEY
      SUPABASE_BUCKET_ID: $SUPABASE_BUCKET_ID
    depends_on:
      - kafka
    networks:
      - dokploy-network
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-app.rule=Host(`compose.clelias-dockploy.my.id`)
      - traefik.http.routers.frontend-app.entrypoints=web
  
  ingestion:
    build: ./ingestion/
    environment:
      QDRANT_API_KEY: $QDRANT_API_KEY
      QDRANT_URL: $QDRANT_URL
      QDRANT_COLLECTION_NAME: $QDRANT_COLLECTION_NAME
      DISCORD_WEBHOOK_URL: $DISCORD_WEBHOOK_URL
    depends_on:
      - kafka
      - image-embedding
    networks:
      - dokploy-network
  
  image-embedding:
    build: ./image-embedding/
    environment:
      REPLICATE_API_TOKEN: $REPLICATE_API_TOKEN
    depends_on:
      - kafka
    networks:
      - dokploy-network

